<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;PartDebug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\NekoBotLibrary\NekoBotLibrary\NekoBotLibrary.csproj" />
    <ProjectReference Include="..\..\..\NekoBot\NekoBotV1.DataBase\NekoBotV1.DataBase.csproj" />
  </ItemGroup>

</Project>
